---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - ssh_key
    - pwdless_sudo
    - xcode-tools
    - geerlingguy.homebrew
    - dotfiles_yadm
    - oh-my-zsh
    - osx-dotfile
    - pwdless_sudo_disable
    - name: geerlingguy.mas
      when: mas_installed_app_ids

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml
