---
- name: Add kotofos user to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ ansible_used_id }}'
    line: '{{ ansible_used_id }} ALL=(ALL) NOPASSWD: ALL'
  become: true
